# Generated by Django 6.0.4 on 2026-04-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='coefficient',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
